module.exports = {
  TERMINAL_STATE_CLOSED: 'TERMINAL_CLOSED',
  TERMINAL_STATE_READY: 'TERMINAL_READY',
  TERMINAL_STATE_ERROR: 'TERMINAL_ERROR',
  TERMINAL_STATE_EXECUTING: 'TERMINAL_STATE_EXECUTING',
};
