module.exports = {
  AICA: 'Adjustable A/C',
  AICO: 'Air Conditioning',
  ALGF: 'Alergy-Free Rooms Avail',
  ALNS: 'All public/private spaces are non-smoking',
  BALC: 'Balcony/Lanai/Terrace',
  BECH: 'Beach',
  BIKE: 'Biking',
  BIKR: 'Bicycle Rental',
  BLRD: 'Billiards',
  BOWL: 'Bowling',
  BRBF: 'Breakfast Buffet',
  BRBQ: 'Bar B Que facilities',
  BRST: 'Bridal Suite',
  CARE: 'Car Rental Desk',
  CASI: 'Casino',
  CHCA: 'Child Care/Baby sit',
  CLNE: 'Chapel/Shrine nearby',
  CNOE: 'Canoeing',
  CNYS: 'Countryside',
  COBR: 'Continental Breakfast',
  COBU: 'Computer Business Centre',
  CPLY: "Children's Playground",
  CTYC: 'City Centre',
  CUEX: 'Currency Exchange',
  CVPK: 'Covered Parking',
  CYCL: 'Cycling',
  DART: 'Darts',
  DIVG: 'Diving',
  DRYC: 'Dry Cleaning',
  DSGN: 'Design/Boutique Hotel',
  ELEV: 'Elevators',
  EXCK: 'Express Check in/Check out',
  EXCT: 'Near Exhibition Centre',
  FARM: 'Family Rooms',
  FD24: 'Front Desk 24/7',
  FEPK: 'Pay Parking',
  FISH: 'Fishing',
  FPRK: 'Free Parking',
  FTDN: 'Fitnesscenters in der Nahe (Kostenlos)',
  FXSV: 'Fax Service',
  GARO: 'Game Room',
  GF3K: 'Golf Course nearby (<3KM)',
  GISH: 'Gift Shop',
  GRDN: 'Garden',
  GYFR: 'Gay Friendly',
  HABR: 'Barber/Hairdresser',
  HAFA: 'Handicap Facilities',
  HATB: 'Turkish Bath (Hammam)',
  HBRI: 'Horseback Riding',
  HEAT: 'Heating',
  HECL: 'Health Club',
  HENE: 'Health Club Nearby',
  HESP: 'Fitness Center or Spa',
  HRBR: 'Harbour',
  HSPI: 'High Speed Internet',
  HWFR: 'Free High Speed Wireless',
  INPK: 'Indoor Parking',
  INPL: 'Indoor Pool',
  INSV: 'Internet service',
  INWI: 'Wi/Fi Wireless LAN',
  IRBD: 'Ironing Board/Trouser Press',
  JZHT: 'Jacuzzi/Hot tub',
  KOKE: 'Karaoke',
  L2GO: 'Lunch to go/packed lunch',
  LAKE: 'Lake',
  LAVA: 'Laundry/Valet',
  LIBY: 'Library',
  LUGE: 'Lounge',
  LUGS: 'Luggage Storage',
  MEFA: 'Meeting Facilities/Conference',
  MNGF: 'Mini Golf',
  MPBR: 'Bar in Middle of Pool',
  MSMA: 'Museum Area',
  MSSG: 'Massage',
  MTNS: 'Mountains',
  NAPO: 'Near Airport',
  NHWY: 'Near Highway',
  NSMR: 'Non-Smoking Room',
  NWPR: 'Newspaper',
  OTWN: 'Old Town',
  OUPK: 'Outdoor Parking',
  OUPL: 'Outdoor Pool',
  PANO: 'Panoramic View',
  PARK: 'Parking',
  PLBR: 'Bar Poolside',
  POOL: 'Pool',
  PRKR: 'Park, Recreation',
  RIVR: 'River',
  ROSE: 'Room Service',
  RSBK: 'Room service Breakfast',
  RTNT: 'Restaurant',
  SAFD: 'Safety Deposit Box',
  SAUN: 'Sauna',
  SBWY: 'Subway near',
  SDPF: 'Soundproofed Rooms',
  SEPA: 'Secured, Guarded parking',
  SHFE: 'Airport Shuttle Surcharge',
  SHFR: 'Free Airport Shuttle',
  SHOE: 'Shoe Shine',
  SHOP: 'Shopping Centre',
  SHTL: 'Shuttle service',
  SKII: 'Skiing',
  SKIS: 'Ski Storage',
  SKSC: 'Ski School',
  SNKL: 'Snorkelling',
  SOLR: 'Solarium',
  SPAA: 'Spa',
  SPAL: 'Small Pets Allowed',
  SQSH: 'Squash Courts',
  STMB: 'Steam Bath/Turkish Bath',
  SVSH: 'Shops in Hotel',
  TBLT: 'Table Tennis',
  TKTS: 'Ticket Service',
  TNBY: 'Near Train Station',
  TNCT: 'Tennis Court',
  TRDK: 'Tour Desk',
  TREE: 'Forest',
  UNIV: 'University',
  V2PK: 'Valet Parking',
  VAPK: 'Valet parking',
  VIPF: 'Very Important Person (VIP) Room Facilities',
  WALK: 'Walking',
  WSRF: 'Windsurfing',
};
